### ISSUE TITLE
Upgrading from SLES12 SP4 to SLES15 SP1 using DMS

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#266] opened 2021-04-09 16:30 UTC
Hi Marcus, 

We are trying to do an upgrade from SLES12 SP4 -> SLES15 SP1, however we are encountering a couple of issues with DMS.
I'm not sure if DMS is something which has been built for a solution like ours, so wanted to know if is supported.

I have been using the above [documentation](https://documentation.suse.com/suse-distribution-migration-system/1.0/pdf/distribution-migration-system_color_en.pdf) to try to perform a SLES major version upgrade [this is the first time we are doing it] and we have been running into issues during the upgrade.

the migration didn’t work because during an upgrade the migration system was not able to reach out to suse repos.
I have setup a rmt server in the environment but the migration fails, since it finds conflicting uuids during boot times and fails to mount the root FS with the same error.
I'm not sure if this is something specific to the image or the process itself is not supported on baremetal servers.
This is something which we are considering as an option for our customers, since this requires minimal effort for the customer for migration and is as seamless as the SP migrations.

Also, please let me know incase this is not the right forum to discuss this issue.

Thanks !!

**Comment by jaawasth** [comment] 2021-04-12 13:49
@schaefi , any ideas ?

**Comment by schaefi** [comment] 2021-04-13 10:13
Hi Jai,

the DMS has been designed to upgrade cloud instances but there is no design aspect that would not allow to use it for baremetal or any other SLE12 system upgrade process. The problem is usually if "zypper migration" can find an upgrade path. In the cloud we know that this upgrade path exists. For any customer specific system we don't know it. Therefore all kinds of issues depending on your registered product, installed software, eventually installed third party software can happen. From what I read here and from the mail thread I think you are running into one of those issues. I also read there is trouble in setting up the network access.

In order to debug all these issues in your environment it would be good to sync up in a teams session. At best with an open debug window for the DMS. You can setup this as follows:

* prior migration create /etc/sle-migration-service.yml and set

   ```yaml
   debug: true
   ```

* prior migration and after the installation of the suse-migration-sle15-activation package edit /boot/grub2/grub.cfg
   search for the "loopback" entry and add the option "console="ttyS0"

* now start the migration. You should be able to connect to the serial console of the machine. This is important because you said you had network issues in the upgrade system. All output will appear on the serial console and on failure the system will not reboot (because of debug set to true) and you get prompted with a login. If you have the system at that stage it would be good to sync up in a meeting

**Comment by schaefi** [comment] 2021-04-13 10:14
And yes this is the wrong place to discuss DMS issues. DMS exists here:
https://github.com/SUSE/suse-migration-services

I'm closing the issue here and hope you have success with setting up a debug environment

**Closed by schaefi** 2021-04-13 10:14 UTC

**Comment by jaawasth** [comment] 2021-04-14 06:40
Hi Marcus, 

Initially  I was facing network issues, but lately its not even reaching that point, to avoid network relate issues, I have for now setup a local rmt server.

During the upgrade when migration system is trying to mount the root file system, it fails everytime and then the process goes on again in loop.

Sure, i can have a debug environment setup, please let me know when would you want to have that session [date / time] , I'll schedule a meeting accordingly.

**Comment by jaawasth** [comment] 2021-04-14 06:41
fyi, filed a bug with DMS https://github.com/SUSE/suse-migration-services/issues/197
thanks for pointing out that project.
