### ISSUE TITLE
VLI only: Need additional boot parameters of "nohz=off skew_tick=1"

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#113] opened 2019-01-24 23:58 UTC
On VLI nodes **only**, we need two additional boot parameters set: `nohz=off skew_tick=1`

Note that these are not needed for the tickless kernel. We only need it for older kernels. Specifically:

- SLES 12 (SP2, SP3, SP4)
- RHEL 7.2/7.3 (just for context, obviously RHEL isn't the topic here)

For newer kernels (i.e. the tickless kernel), use the kernel default boot command line parameters.

**Comment by rjschwei** [comment] 2019-01-25 12:16
We agreed to no do SLES 12 SP2, and SLES 12 SP4 has the same kernel as SLES 15, we'll investigate where this might apply.

**Comment by schaefi** [comment] 2019-02-01 08:57
Sorry I don't see why we need to set this. SLE12-SP4 and SLE15 are both tickless kernels. SP2 and SP3 is out of scope. For me this one does not create an action item.

**Comment by rjschwei** [comment] 2019-02-01 12:35
Since this is SLES For SAP SLES 12 SP3 For SAP is still relevant, we'll set the parameters in the image build.

**Comment by jeffaco** [comment] 2019-02-01 17:56
I understand what you're saying, but my hardware vendor is saying something different:

>But as I said before they are NOT the same kernel patch release. There are some 63k lines of code difference between the SLES12sp4 kernel and SLES15 kernel. But regardless, for now, ALL SLES and RHEL kernels are to be run with the old periodic clock kernel (ie nohz=off, skew_tick=1) on the legacy SGI UV300 line of hardware (UV300, MC990, SuperDome Flex). 
>
>Sorry if I am being unclear. And please do not ask me why the sp4 kernel is newer than the sles15..... :)
>
>netinst/sles> find 12sp4/* -name "*kernel-default*64.rpm"
12sp4/aarch64/gm/suse/aarch64/kernel-default-4.12.14-94.41.1.aarch64.rpm
>
>netinst/sles> find 15/* -name "*kernel-default*64.rpm"
15/aarch64/gm/Module-Basesystem/aarch64/kernel-default-4.12.14-23.1.aarch64.rpm

I'm not entirely sure what the kernel version situation is in SLES 12 SP4 vs. SLES 15 (I never booted SLES 15 yet, and I only booted SLES 12 SP4 yesterday since you kind folks gave me a test image).

I just need to make sure that the kernel parameters (for VLI) are set properly on older (non-tickless) kernels.

Does SLES 12 SP4 really have the tickless kernel?

**Comment by rjschwei** [comment] 2019-02-01 20:42
Execute commands as root:

On SLES 15
`~> uname -a
Linux ip-10-0-0-12 4.12.14-25.13-default
~> grep PRETTY /etc/os-release
PRETTY_NAME="SUSE Linux Enterprise Server 15"
~> cp /proc/config.gz .
~> gunzip config.gz
~> grep -i NO_HZ config
CONFIG_NO_HZ_COMMON=y
# CONFIG_NO_HZ_IDLE is not set
CONFIG_NO_HZ_FULL=y
# CONFIG_NO_HZ_FULL_ALL is not set
# CONFIG_NO_HZ_FULL_SYSIDLE is not set
CONFIG_NO_HZ=y
`

On SLES 12 SP4:
`~> uname -a
Linux ip-172-30-3-24 4.12.14-94.41-default
~> grep PRETTY /etc/os-release
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP4"
~> cp /proc/config.gz .
~> gunzip config.gz
~> grep -i NO_HZ config
CONFIG_NO_HZ_COMMON=y
# CONFIG_NO_HZ_IDLE is not set
CONFIG_NO_HZ_FULL=y
# CONFIG_NO_HZ_FULL_ALL is not set
# CONFIG_NO_HZ_FULL_SYSIDLE is not set
CONFIG_NO_HZ=y
`

And even on SLES 12 SP3
`~> uname -a
Linux ip-172-30-3-211 4.4.143-94.47-default
~> grep PRETTY /etc/os-release
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
~> cp /proc/config.gz .
~> gunzip config.gz
~> grep -i NO_HZ config
CONFIG_NO_HZ_COMMON=y
# CONFIG_NO_HZ_IDLE is not set
CONFIG_NO_HZ_FULL=y
# CONFIG_NO_HZ_FULL_ALL is not set
# CONFIG_NO_HZ_FULL_SYSIDLE is not set
CONFIG_NO_HZ=y
`

So there is no action required on our side. Hopefully that is sufficient data. Anyway if your HW vendor has data that shows the SLES kernel generates timer events even with these settings a bug should be filed with appropriate supporting data.

**Closed by rjschwei** 2019-02-01 20:42 UTC
Labels: question

**Comment by rjschwei** [comment] 2019-02-01 20:43
In the previous comment everything that is bold is a comment, i.e. proceeded by a hashtag. If GitHub could just fix their parser and not treat hashtag special in code blocks that would really be nice.

**Comment by rjschwei** [comment] 2019-02-01 20:54
OK after all of this... I found:

> There is also a boot parameter "nohz=" that can be used to disable
dyntick-idle mode in CONFIG_NO_HZ_IDLE=y kernels by specifying "nohz=off".
By default, CONFIG_NO_HZ_IDLE=y kernels boot with "nohz=on", enabling
dyntick-idle mode.

Got to love abbreviations and double negations. Setting all VLI image builds up with "nohz=off"

[1] https://www.kernel.org/doc/Documentation/timers/NO_HZ.txt

**Comment by rjschwei** [comment] 2019-02-01 21:16
Both have been set in the image build

**Comment by jeffaco** [comment] 2019-02-01 21:17
Okay, is this for SLES 12 SP3? Or all images?

What about the guidance that this isn't needed for SLES 15? Are they harmless there?

**Comment by rjschwei** [comment] 2019-02-01 21:36
OK, confusing. SO to make it simple I have set

nohz=off skew_tick=1

for all image builds SLES 12 Sp3, SLES 12 SP4, SLES 15 SP1 and it will be carried to the SLES 15 image build when we set it up.

**Comment by jeffaco** [comment] 2019-02-01 22:49
This is exceedingly confusing. From my original message that started all this:

> On VLI nodes **only**, we need two additional boot parameters set: `nohz=off skew_tick=1`
> 
> Note that these are not needed for the tickless kernel. We only need it for older kernels. Specifically:
> 
>     * SLES 12 (SP2, SP3, SP4)
> 
>     * RHEL 7.2/7.3 (just for context, obviously RHEL isn't the topic here)
> 
> 
> For newer kernels (i.e. the tickless kernel), use the kernel default boot command line parameters.

So this says we do not need it for SLES 15, but do need it for SLES 12 SPx ...

**Comment by rjschwei** [comment] 2019-02-04 12:34
Sorry I am not certain what is confusing about my previous comment:

> ...to make it simple I have set
>
>nohz=off skew_tick=1
>
>for all image builds SLES 12 Sp3, SLES 12 SP4, SLES 15 SP1 and it will be carried to the SLES 15 image build when we set it up.

If we set the values on the kernel command line the build configuration of the kernel is somewhat immaterial and we get what we want.

**Comment by jeffaco** [comment] 2019-02-04 16:36
My confusion is that the hardware vendor said these boot options were not necessary for SLES 15. Yet you're setting them on SLES 15 ... and I'm not sure what sort of affect that will have.

Are you saying that we need these for SLES 15 as well as SLES 12? Or did you miss that the hardware vendor said don't do that for SLES 15?

Thanks ...

**Comment by rjschwei** [comment] 2019-02-04 21:10
Sorry, I really don't know how to say this in any other way, thus most of whatever follows is a repeat of what has been stated previously.

In a previous comment I have shown that all our kernels (SLES 12 SP3, SLES 12 SP4, and SLES 15) are configured the same way. You can easily reproduce this as I have shown how to get the proper configuration options. Tick-less is a configuration option!

I have also provided a select section from the kernel internal documentation about NO_HZ and have provided a reference where to find it.

In an effort to avoid this confusion and having people have to interpret things by researching over and over what is needed I have set the required kernel command line options in all image builds. This also ensures that these settings will be carried forward as we release new distributions. Further,
for all kernels (SLES 12 SP3, SLES 12 SP4, and SLES 15) our kernel configuration has

`CONFIG_NO_HZ_IDLE is not set`

if it is not set in the config file given to the kernel build the default applies.  The kernel doc implies, it does not explicitly state, that the default for CONFIG_NO_HZ_IDLE is

`CONFIG_NO_HZ_IDLE=y`

Then in the snippet I provided previously it states that with

`CONFIG_NO_HZ_IDLE=y`

the default is to start with

`nohz=on`

but if we want it off then we'll have to change this. And only the behavior of CONFIG_NO_HZ_IDLE is influenced with the nohz setting, also documented in the kernel doc.

Again, this is basically a repeat of information provided previously.

If the HW vendor states they want one setting for SLES 12 SP3 and maybe something else for other versions of SLES then they are ignoring the actual kernel configuration, as shown it is the same for all kernels in question in this discussion. We will set what is needed, but it has to be consistent with reality. Given that ALL 3  kernels are configured the same with respect to idle clock ticks it simply makes no sense to state do this for SLES 12 SP3, that for SLES 12 SP4 and something else for SLES 15.

**Comment by jeffaco** [comment] 2019-02-04 22:08
I think the HW vendor is unaware that the SLES 12 kernel can be configured to be tick-less. I'll pass this along. Thanks for the clarification.
