### ISSUE TITLE
SLES12-SP4 need manual intervention to boot.

### ISSUE THREAD

**Issue by prtyag** [SUSE-Enceladus/azure-li-services#232] opened 2020-07-02 12:45 UTC
Hi,
Current VLI test image SLES12-SP4-SAP-Azure-VLI-BYOS.x86_64-0.0.23-Devel-Build33.2.raw is not booting up on a VLI system. I can see message on the console saying "reboot: system halted". Console output screenshot is below:
<img width="933" alt="error_screen_1" src="https://user-images.githubusercontent.com/51941156/86360057-79ead600-bc8f-11ea-885a-13630757f24e.PNG">
<img width="788" alt="error_screen_2" src="https://user-images.githubusercontent.com/51941156/86360229-b1598280-bc8f-11ea-8c32-b6016a56e1ed.PNG">

After this point I reboot the system and it came up.

**Comment by schaefi** [comment] 2020-07-03 09:11
I'll give it a test. So far I see the xfs_repair failed with a segmentation fault which is the reason why you got stuck

I'll test the appliance on a VM and see if I can reproduce this

**Comment by schaefi** [comment] 2020-07-03 09:15
The boot in a VM worked flawlessly. Could this maybe be a problem of your storage system and/or the LUN you bumped the image onto. See the XFS rootfs is not clean which it is if you only look at the image file. Also the xfs_repair failed with a segmentation fault. That really points to a problem with the storage or the drivers (fb) or both.

**Comment by schaefi** [comment] 2020-07-03 09:18
Very strange is also that it boots on a second attempt, if the xfs root is broken I would have expected the same situation on reboot

**Comment by prtyag** [comment] 2020-07-03 09:23
> The boot in a VM worked flawlessly. Could this maybe be a problem of your storage system and/or the LUN you bumped the image onto. See the XFS rootfs is not clean which it is if you only look at the image file. Also the xfs_repair failed with a segmentation fault. That really points to a problem with the storage or the drivers (fb) or both.

If the drivers(fb) or storage has a problem then we would have got the same response from other images as well but that's not the  case other images are booting up fine.

**Comment by prtyag** [comment] 2020-07-03 09:24
> Very strange is also that it boots on a second attempt, if the xfs root is broken I would have expected the same situation on reboot

Yes I'm also wondering the same.

**Comment by schaefi** [comment] 2020-07-03 09:32
Hmm, there is really little I can do here. Can you repeat that xfs_repair segmentation fault any time ? Meaning is this a safe reproducer ? If yes I suggest you open a bugzilla entry against the xfsprogs maintainer (ailiopoulos@suse.com) and include the segfault error as shown in your output. The image can serve as a reproducer on your end.

**Comment by schaefi** [comment] 2020-07-24 07:19
@prtyag I'm closing this on behalf of the bug report you created against xfs. As there is little we can do here I think this history can be closed. Thanks

**Closed by schaefi** 2020-07-24 07:19 UTC
