### ISSUE TITLE
LI Prod image dropping to dracut during boot randomly

### ISSUE THREAD

**Issue by jaawasth** [SUSE-Enceladus/azure-li-services#255] opened 2020-11-24 05:45 UTC
Hi Marcus, 

We have got latest prod images for SLES12 SP4 but its dropping to dracut shell during bootup.
Please note this problem happens only sometimes [seems like a race condition??] and is very similar to the issue described here [https://github.com/SUSE-Enceladus/azure-li-services/issues/220]

Please see below the new snapshot attached of the error we see.
Since this issue is ongoing for sometime, can we get a new debug image with kiwi enabled, please let me know what files you would like me to catch hold off.

 
![image_issue_octavian_sles12sp4](https://user-images.githubusercontent.com/71845324/100053542-424f1700-2e46-11eb-83a5-c3cf9f05334d.png)

Thanks !!

**Comment by jaawasth** [comment] 2020-11-24 05:47
Also, is there some way we can cath through regressions before releasing these images ?

**Comment by rjschwei** [comment] 2020-11-24 20:42
> Also, is there some way we can cath through regressions before releasing these images ?

We do not have an environment for testing. We can only do rudimentary testing. Images get tested in a KVM based test environment which will obviously have very different boot characteristics then the HW. All packages in the images go through maintenance QA testing before being released.

With no access to the environment we rely on the Microsoft team to do final acceptance testing.

**Comment by jaawasth** [comment] 2020-11-25 05:23
@rjschwei , thanks, but is there a way, even in our environemnt, as to how we can catch this bug, without actually deploying the image on the system multiple times[as that is a time consuming process ?]
@schaefi  any updates on the bug ?

**Comment by rjschwei** [comment] 2020-11-25 12:39
@jaawasth if it really turns out to be a timing issue then the answer would be "no". That said, based on what we know so far I am not convinced this is a timing issue. But we need logs, especially the kiwi log in order to gain a better understanding of what is going on.

**Comment by jaawasth** [comment] 2020-11-25 13:51
@rjschwei thanks, can you please provide me a debug image with debug enabled, as this is not reproducible in all boots, i'll run  a script to to boot with new os everytime to reproduce this issue, hence will not be able to set the debug manually.

**Comment by schaefi** [comment] 2020-11-26 09:20
Hmm, this issue is weird and I can't reproduce it. It seems at the time of the resize the device to resize is busy. The only service that can hold a busy state is the systemd-fsck-root.service, but this service is masked by us prior resize. So without a reproducer I don't know where the busy state comes from. I agree it must be some sort of race condition as it happens only occasionally

The script you are writing to reproduce the failure condition is a good idea. You can just take the image in question and
modify it yourself for debugging as follows:

```
$ cp SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-*.raw.xz my-debug-image.raw.xz
$ xz -d my-debug-image.raw.xz
$ sudo kpartx -a my-debug-image.raw
$ sudo mount /dev/mapper/loop0p2 /mnt

==> Edit the file /mnt/boot/grub2/grub.cfg with your favorite editor and root permission e.g

$ sudo vi /mnt/boot/grub2/grub.cfg

==> Search for the entries that starts with root=UUID and append the following to the end of each line

       rd.debug rd.kiwi.debug rd.shell console=ttyS0

==> Save the file and continue with

$ sudo umount /mnt
$ sudo kpartx -d /dev/loop0
$ sudo losetup -d /dev/loop0
```

You have now prepared a debugging image ```my-debug-image.raw``` which you can handle the same way as the other images. 
If you hit the issue with this image you will be dropped into a rescue shell and we can have a conversation and a debugging session.

Please note the setting ```console=ttyS0``` will cause all kernel messages and also the debug shell to be opened on a serial console. For debugging and also for fetching log data this is the preferred way. However I don't know how the hardware vendor handles this and if it works with the IPMI management console your hardware vendor uses. This part stays on your side to clarify with the IT people to arrange for a serial console.

In any case for debugging issues like that a serial console is preferred. If you for some reason cannot manage to get a serial console then leave out the console parameter in the debugging parameters

Thanks, let's hope we find the reason for this one, it's strange

**Comment by schaefi** [comment] 2020-11-26 09:32
My gut feeling also tells me that this is most probably an issue with the multipath device mapper being started prior disk resize...

**Comment by schaefi** [comment] 2020-11-26 09:51
@jaawasth I think I have an idea what could cause this. Can you give me access to an installed system, I'd like to check the multipath situation on a correctly deployed system to prove my idea. Please follow up with me on e-mail to get ssh access. Thanks much

**Comment by schaefi** [comment] 2020-11-26 10:45
The really problematic part is that from the picture I saw it's directly mounting /dev/sde1 which would be not a good idea in a mapped disk like on multipath. I have double checked if I can find a mistake but in all my tests the correct device map is used and not the linux node name. So it stays a strange issue and we need the debugging information as I have explained. Thanks

**Comment by jaawasth** [comment] 2020-11-26 10:46
@schaefi yes, sure, i can get you access to the blade

**Comment by schaefi** [comment] 2020-12-02 14:47
Thanks Jai for the jump host setup. I was able to login and check the situation. So here is what I found.
On a successful run the log contains:

```
////lib/kiwi-lib.sh@54(lookup_disk_device_from_root): multipath -l -v1 /dev/sdg
///lib/kiwi-lib.sh@54(lookup_disk_device_from_root): for wwn in '$(multipath -l -v1 "${disk_device}")
'
///lib/kiwi-lib.sh@55(lookup_disk_device_from_root): '[' -e /dev/mapper/3600a09803830423066244d6f302d
5142 ']'
///lib/kiwi-lib.sh@56(lookup_disk_device_from_root): disk_device=/dev/mapper/3600a09803830423066244d6
f302d5142
///lib/kiwi-lib.sh@57(lookup_disk_device_from_root): break
///lib/kiwi-lib.sh@61(lookup_disk_device_from_root): echo /dev/mapper/3600a09803830423066244d6f302d51
42
///lib/dracut/hooks/pre-mount/20-kiwi-repart-disk.sh@26(initialize): disk=/dev/mapper/3600a0980383042
3066244d6f302d5142
```

So you see the setting for ```disk=``` is correctly set to the multipath mapped file ```/dev/mapper/...```

When it fails the setting for ```disk=``` is some unix node. In your case ```/dev/sde```

In a multipath system the direct access of the linux node is not possible because multipath holds a device mapper lock on it

Now you said this happens only sometimes. So I guess at the time kiwi calls ```multipath -l -v1 /dev/...``` it seems we can't be 100% that the multipath maps have already been settled

The pre-mount hooks in systemd are all executed in parallel so we need to find a way to serialize this

**Comment by schaefi** [comment] 2020-12-02 14:47
A proper fix for this has to happen in kiwi

**Comment by jaawasth** [comment] 2020-12-02 15:06
thanks @schaefi , i have few questions.
1. is there a dependent team we need to open the kiwi bug on ?
2. how long do we expect this to take ?
3. from the error it looks like, the device is already mounted and its not able to resize it, can we safely conclude its because system is not able to find the multipath device if because its not initiliazed yet ?

**Comment by schaefi** [comment] 2020-12-02 15:28
> is there a dependent team we need to open the kiwi bug on ?

nope I'm leading this ship :)

> how long do we expect this to take ?

I have created an PR, see the reference here. This needs testing and merge. From there I can send you a testing image. This will be done in ~1week. I would say you then give it some time to check if it really fixes the issue. After that I need to port the fix to the kiwi in SLE and submit to the SUSE namespace (I assume this will take ~2-3weeks for approval and QA)

> from the error it looks like, the device is already mounted and its not able to resize it,

nope, it's not mounted but the device mapper holds a busy state on it. I can assure you this is because kiwi uses the wrong device (not the multipath device). You can also check this yourself. On all systems it has worked you see in ```/run/initramfs/log/boot.kiwi``` something like ```root_map=/dev/mapper/``` and on all systems it has not worked you will see some linux node e.g /dev/sde

**Comment by jaawasth** [comment] 2020-12-02 15:31
thanks for the answers,  looking forward to the debug image !

**Comment by schaefi** [comment] 2020-12-03 15:39
* https://bugzilla.suse.com/show_bug.cgi?id=1179562

has been opened to track the backport. The fix has been merged upstream and I ported to sle15-sp1(sp2/sp3) and sle12-sp4, sle12-sp5

I will now build the Devel images with the kiwi including the fix. I'll let you know once an image with the fix for testing is available

**Comment by schaefi** [comment] 2020-12-04 13:50
@jaawasth I'm ready with all patches and would like to send you a testing image. Which LI/VLI image do you want to use for testing. I think it was SLES12-SP4-SAP-Azure-LI-BYOS correct ?

**Comment by jaawasth** [comment] 2020-12-04 16:26
@schaefi , thanks, yes, SLES12 SP4, LI image is the one we want for testing.

**Comment by schaefi** [comment] 2020-12-07 11:15
Hi Jai, I've sent you an e-mail with a testing image. Let's give this is a test. If you have deployed it once can you send along the file:

```
/run/initramfs/log/boot.kiwi
```

If it worked once, please include this image in your testing loop. I hope this will fix the race condition

Thanks

**Comment by jaawasth** [comment] 2020-12-07 11:20
Hi Marcus,

Sure, let me deploy and send you the file, post that ill include it in the test loop.

Thanks !!

**Comment by jaawasth** [comment] 2020-12-07 11:47
Hi Marcus,

Please find the boot.kiwi file
https://imagestoreaccount.blob.core.windows.net/logs/SLES12-SP4-SAP-Azure-LI-BYOS.x86_64-1.0.14-Devel-Build59.1.boot.kiwi?sp=r&st=2020-12-07T11:46:12Z&se=2021-04-09T19:46:12Z&spr=https&sv=2019-12-12&sr=b&sig=AWWr%2FzvAdIftISYQBwSUsANwdqGoTPE4E65eRgxKv2k%3D

Please let me know if it can be included in the test loop now ?

Thanks !!

**Comment by schaefi** [comment] 2020-12-07 14:09
Thanks, looks good

```
++++ get_mapped_multipath_disk /dev/sda
++ set_root_map /dev/mapper/3600a09803830423066244d6f302d5142-part2
```

You can put that image to the testing loop

PS:
it looks like you are responding via e-mail to github. This is a nice feature but only if you could avoid sending the same mail text again :) I have a hard read on github to find the important part of the message. Would be great if you can send along only the relevant bits. Thanks much

**Comment by jaawasth** [comment] 2020-12-07 15:40
Sure, i'll respond directly here.

**Comment by schaefi** [comment] 2020-12-08 09:07
Thanks much :+1:

**Comment by schaefi** [comment] 2020-12-13 17:10
@jaawasth how is it, silence means everything is just working brilliant ;) ?

**Comment by jaawasth** [comment] 2020-12-14 06:00
@schaefi , setting up the script will take sometime as we ahve complete isolation of mgmt n/w, will update you as soon im done :)

**Comment by schaefi** [comment] 2021-02-25 14:46
@jaawasth is there any new information about this topic ? If not I consider this as fixed since I'm confident the patch fixed the race condition and I can't reproduce the issue anymore. If there are no further objections the issue will be closed in the next 7 days. Thanks

**Comment by schaefi** [comment] 2021-03-05 10:07
I consider this as fixed

**Closed by schaefi** 2021-03-05 10:07 UTC
Labels: AwaitingFeedback
