### ISSUE TITLE
Production image "SLES12-SP3-SAP-Azure-LI-BYOS.x86_64-1.0.55-Build1.2.raw" fails to boot

### ISSUE THREAD

**Issue by jeffaco** [SUSE-Enceladus/azure-li-services#145] opened 2019-05-17 17:17 UTC
In testing the last production image release, SLES 12 SP3 (`SLES12-SP3-SAP-Azure-LI-BYOS.x86_64-1.0.55-Build1.2.raw`) doesn't boot properly.

Observations:

1. Shortly after the boot process commences, a script starts executing, it's output going to the system console. This script is running for quite a while and then eventually triggers a reboot. This was captured as Screen Shot 1:
<img width="1146" alt="Screen Shot 2019-05-17 at 9 34 19 AM" src="https://user-images.githubusercontent.com/13700943/57944632-79755d00-788c-11e9-98e3-116d2666e9cf.png">

2. Early in the boot sequence, I get some "errors"/output on the console, a which point the script starts sending output shortly thereafter (ending in Screen Shot 1 above). This was captured as Screen Shot 2:
<img width="856" alt="Screen Shot 2019-05-17 at 9 55 48 AM" src="https://user-images.githubusercontent.com/13700943/57944721-bb060800-788c-11e9-93a6-83ee67107cf6.png">

It' difficult for me to collect further information, as I have no opportunity to actually log into the node. If you need further information, let me know what I can do to collect it.

Note that SLES 12 SP4 and SLES 15 do not experience this issue; they boot up fine.

Hopefully this is something simple and a new image for SLES 12 SP3 can be provided?

**Comment by schaefi** [comment] 2019-05-19 16:55
Shocking news :(

I can reproduce this but I have no idea what is causing this as of now. So the problem is clear, the kernel device tree does not provide and disk devices. Actually the entire path ```/dev/disk``` is missing. I have done many tests to check if any kiwi change could have caused this and also tried building the image against SP2. I always got the same result, no storage devices. I can see scsi modules are loaded and the kernel has all symbols and modules it needs to actually drive the disk.

So to say I'm clueless what has happened. Currently I would say that kernel update triggered it.

@rjschwei any help would be much appreciated. Do you have any idea what exactly has changed on the kernel side that could have caused this ? or any hint that helps to find the reason. If you boot the image with the boot option:

```
kiwidebug=1
```

you will land in a shell and that gives you some space for experiments. You will see there are only ramdisk devices available and nothing else. I checked if udev is running, also the loaded modules and could not find anything. It looks like no storage devices got attached to the system which is of course completely wrong. Also dmesg doesn't give me a hint

pretty pretty bad news :(

**Comment by schaefi** [comment] 2019-05-19 16:56
I have done testing in qemu so far

**Comment by schaefi** [comment] 2019-05-20 07:19
@rjschwei furthermore this is not only an issue for this image. It seems all images also the pubcloud ones for EC2, Azure and GCE in SLE12 SP3 are non functional now. None of them can find their root device because there are no storage devices available below /dev/disk

**Comment by schaefi** [comment] 2019-05-20 07:25
SP4 and SLE15 works. So this targets SLES12-SP3 but all of it :(

**Comment by rjschwei** [comment] 2019-05-20 13:47
Well all devices, even root are handled via udev and udev is delivered as part of systemd these days. So it is possible that a systemd update is responsible for the problem. Sounds like either no events via udev are triggered, there is an issue with the udev block storage rules, or udev events are being dropped. I'd say we want a bug assigned to our systemd maintainers.

**Comment by jeffaco** [comment] 2019-05-20 15:50
I was going to point out that SLES 12 SP4 and SLES 15 do not share this problem. Then I saw you already did, and I saw I mentioned that in my original post.

Since you're replicating it, I guess I can't really do more testing to help. But if there is something I can do to help you folks isolate this or pin it down, let me know. Given that SLES 12 SP4 works, perhaps we might want to try the SP4 kernel in an SP3 image (just to see if it actually boots)? This, if it can be done, would at least help isolate where the problem lies (kernel, systemd, udev, etc) ...

**Comment by schaefi** [comment] 2019-05-20 16:00
Thanks for offering your help. I'm already in an e-mail conversation with the crowd. So you might remember I uploaded the testing image for SLES12-SP3 on 2019-05-07T10:31:43+00:00. This is still in the Azure testing bucket and works. So I took this date as a reference. In between there were changes to the kernel and systemd. I doubt the kernel is the problem just because people are relatively careful here. The systemd update could be the reason but it's all just a wild guess

We'll keep you posted and thanks for offering help on the testing side.

**Comment by schaefi** [comment] 2019-05-22 07:38
@jeffaco we identified the problem. It was an update of udev that made it into the SUSE namespace and caused all the trouble. For details see:

* https://bugzilla.suse.com/show_bug.cgi?id=1135762

I realized the update made it to basically all SLES code streams. That means basically all of SLES is affected. I expect this to be handled as critical bug that has to be fixed immediately.

I let you know when a new udev update is available that fixes the image build.

I can just ask for your patience because this outside of my control. The bug is open the prio is set now the udev people at suse has to move

**Comment by schaefi** [comment] 2019-05-24 07:40
@jeffaco good news

The bug is fixed. It has turned out that the change in udev introduced a behavior change that in that form never should have been released. Anyway *s* happens and we could add a fix to the appliance builder to handle that change correctly. This change has now been released and a new production image was built.

I'm currently in the process of uploading the image to the publishing account. Please note I have deleted
the broken production image: SLES12-SP3-SAP-Azure-LI-BYOS.x86_64-1.0.55-Build1.2.raw.xz from the bucket.

**Comment by schaefi** [comment] 2019-05-24 09:36
A new production image has been uploaded. Please find the mail with the sas url in your inbox

**Closed by schaefi** 2019-05-24 09:36 UTC
Labels: bug
