### ISSUE TITLE
LI: SLES 12 SP4 doesn't create SWAP volume properly

### ISSUE THREAD

**Issue by hrushib** [SUSE-Enceladus/azure-li-services#163] opened 2019-07-04 19:56 UTC
Recent SLES 12 SP4 image not creating SWAP volume properly. `free` command on the SLES 12 SP4 provisioned server returns following output. 

```
# free
             total       used       free     shared    buffers     cached
Mem:    2113086544  129017920 1984068624     644732      14508   14490308
-/+ buffers/cache:  114513104 1998573440
Swap:            0          0          0
```

Request you to look at it at high priority as this is impacting production scenario. In case simple manual steps available for fixing it in desired manner then please share them to unblock us.

**Comment by schaefi** [comment] 2019-07-05 09:38
We need a bit more information about this one. Can you please provide the output of:

```
swapon --show
```

If this command does not list a swap space please repeat the initial deployment process and at boot time 
when the bootloader shows its menu, hit the Escape key and add the following boot option:

```
rd.kiwi.debug
```

The system boots up now and in the end you get a log file:

```
/run/initramfs/log/boot.kiwi
```

Attach that log file please

Thanks

**Comment by hrushib** [comment] 2019-07-05 15:57
`swapon --show` didn't return any thing so as per your instructions we ran `rd.kiwi.debug` command and output file is attached.
[boot.kiwi.txt](https://github.com/SUSE-Enceladus/azure-li-services/files/3363386/boot.kiwi.txt)

**Comment by schaefi** [comment] 2019-07-08 09:22
@hrushib thanks for the details. This was very helpful. I think I found the bug and it turns out to be a problem in the kiwi image builder. I have created a fix in the respective project.

**Comment by schaefi** [comment] 2019-07-08 16:21
Tested the patch in kiwi with a new image build and it worked in my virtual environment.
We will provide new testing images if we have a fix for #162 available

**Comment by hrushib** [comment] 2019-07-09 05:49
@schaefi thanks for quick response to investigate and fix the issue. 

Meanwhile, please provide manual steps to properly configure SWAP volume from the state left by the setup with this issue to desired state of SWAP volume configuration.

**Comment by schaefi** [comment] 2019-07-15 09:12
> Meanwhile, please provide manual steps to properly configure SWAP volume

You can do this as follows:

1. Find the partition that was intended to hold the swap space. kiwi has created the partition but due to 
    the bug did not create the swap space on it. You can find the partition if you call as root:

    ```
    $ fdisk -l
    ```

   Lookup the device that that has the type (82) Linux swap

2. If you have the device call as root:

    ```
    $ mkswap /dev/<the-device>
    $ swapon /dev/<the-device>
    ```

**Comment by hrushib** [comment] 2019-07-16 08:22
Thanks @schaefi.

**Comment by schaefi** [comment] 2019-08-27 09:29
This change has landed in SUSE:SLE-12-SP4:Update

**Closed by schaefi** 2019-08-27 09:29 UTC

**Comment by hrushib** [comment] 2019-08-27 10:03
Thanks!
